### ISSUE TITLE
Unable to log in?

### ISSUE THREAD

**Issue by artem1919** [Darkr4ptor/Servidor-Chapter-1-WarRock#5]
Hi. Although a basic tutorial would be nice to have, I managed to set up and launch everything anyway.

When trying to log in I got stuck with some issue. Once I click a server, I get an error saying it has "Exceeded maximum capacity".
Am I doing something wrong? Which version am I supposed to be using? 
![image](https://user-images.githubusercontent.com/13397494/48094337-99133500-e21a-11e8-88e3-cc64fe6e9fab.png)

Also, do you need some play testers? Is this project alive?

**Comment by Darkr4ptor** [comment]
Hi, this issue is client-related: wrong version. Are you updating your client to PF-20?

**Comment by artem1919** [comment]
I'm not sure what PF-20 means.
I'm using the 258:441M version, which is compatible with CodeDragon's original server.
[Basically this one.](http://www.4players.de/4players.php/download_info/Downloads/Download/45896/War_Rock/Client.html)

**Comment by Darkr4ptor** [comment]
I'll try to upload those official patches to you today. You are definitely using an older version than us.

**Comment by Darkr4ptor** [comment]
PF17 -> https://file.io/gEnLBR
PF18 -> https://file.io/kl36sY
PF19 -> https://file.io/pfT29T
PF20 -> https://file.io/YwhI3R

Here you are. Install them in ascending order (from 17 to 20). Overwrite when asked to do so. Keep in mind that AFTER updating you must edit the login address again (login.warrock.net) in the executable UNLESS you are setting it up in hosts already.

**Comment by sweetriverfish** [comment]
All the links lead to a 404 page.

**Comment by Darkr4ptor** [comment]
Try these: 

17 https://mega.nz/#!cMhxGKZR!GRX7bFxzWuiG0TuR5HPb9NQZdeawEDajdMcU8eDnYxA
18
https://mega.nz/#!AF4CVR5R!hMRur1KXLSpays8eHjCf_KbiEpFI81Zlax1bCFbdBP8
19
https://mega.nz/#!MdBRlRiT!xVLox5LjlfztbxGa9qQJiDlT8laFu6KDvRLMdc-3vng0
 20
https://mega.nz/#!lNZGjAbQ!3ZFLCVuRpWvFFs1LishcavkIZ1h2OBOjuOryEwARvmQ

**Comment by sweetriverfish** [comment]
Yeah that works. 

So, as for my earlier question, do you need any play testers? Is this project alive?
My coding is pretty bad but I definitely have time to test stuff.

![image](https://user-images.githubusercontent.com/13397494/48672384-e1e1bc80-eb3d-11e8-8040-6a8cd22526a7.png)
Here's one problem when trying to create a new account.

**Comment by Darkr4ptor** [comment]
To summarize your questions:

1. Is this project alive? Yes, but with some caveats: the repo you see is heavily customized to suit our old server with a custom client. It's not intended for hands-free installation. For instance, our client is PF-23 based, but WarRock.exe itself was heavily customized.

2. New accounts: just edit the row using a MySQL editor and it should work fine.
 
3. I'm currently writing a new emu, based on PF-20 stock client. It is coded in .NET Core 2.0 to support Linux servers. The idea behind it is to provide an open-source, noob friendly server.

**Comment by sweetriverfish** [comment]
Yeah I managed to create accounts and stuff. Is reporting issues/trying to fix them myself on this repo a useful thing? I see you created another one 12 hours ago, should I go on that one?

Also 1 more question (sorry for being annoying): Is the game supposed to crash on item buys/selection? Trying to buy a m134 minigun causes my game to crash. Trying equip m60 causes it to crash as well. There are more examples. Maybe I'm missing some patches or stuff?

**Comment by Darkr4ptor** [comment]
Crashes: Actually a security thing. As I commented earlier, this server is made for a heavily customized client that allowed stuff such as 3-days buy or a different code for M60. Those client changes are also present on the database, so yes, some stuff will crash due to missmatch. Adapting your DB to suit your needs should fix the crashes.

Reporting issues: Yeah, feel free. Most of them will be client-related but who knows.

Other repo: still a WIP. You can't even launch a server with the files provided. I'm currently working on the Auth server, but stay tuned.

**Comment by sweetriverfish** [comment]
Well I've been playing it for around 3 hours with someone, so so far here's all the issues I've had:

1. Crashes when buying and equipping stuff.
2. The database error when creating new accounts which I've showed earlier.
3. Medic kit not healing, adrenaline not recovering health. (Medic box does seem to work fine, however it grants less health than what I remember it did. Maybe I just didn't play the game for too long?)
4. During some match both me and my friend were randomly unable to damage each other. This only happened once and I'm not sure what caused it.

I'm not sure which one is client related and which one is server related so I don't want to spam issues, but there's the list so far.

Aside that, thanks for your help with launching the game and the server code. I've had fun playing it for a few hours.
